### ISSUE TITLE
 undefined method `trending' for Giphy:Module

### ISSUE THREAD

**Issue by chaosxregulus** [sebasoga/giphy#8]
Hello!

I can't seem to call trending. I do see recent tho.

Thanks!

**Comment by frubesss** [comment]
Hi,

I am also having an issue regarding this:

NoMethodError: undefined method `trending' for Giphy:Module

Any update on this chaos?

Thanks

**Comment by sebasoga** [comment]
@chaosxregulus, @frubesss just released version `3.0.0` of the gem which includes the bug fix. Upgrade to that version and you should no longer get this issue.
